project:
  type: website
  output-dir: docs

website:
  title: "Crickles"
  description: "Heart health insights for endurance sports"
  favicon: favicon.ico
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Navigator"
        href: app.qmd
      - text: "Research"
        menu:
          - text: "Sustainable Performance"
            href: sustainable.qmd
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: 
      - custom-header.css
      - contact-form.css
  


