---
title: "About"
---

## Why Crickles?

Crickles provides cardiac stress analysis calculated from the activities you record on your sports devices so that while you're keeping fit you have tools to help you quantify whether and when you risk doing too much. We created it because none of the other fitness apps do an adequate job of this one thing. The features that matter to Crickles are:

1.  There is a metric that preferences heart rate data to model the stress incurred from any sports activity captured on a watch, computer or training platform. In Crickles this is called the Cardiac Stress Score (CSS).
2.  The models must be credible and ideally described openly so that you can see how it works.
3.  While being capable of using whatever instrumentation is available, such as chest strap heart rate monitors, sports watches or power meters, the analysis must not diverge dramatically in aggregate according to the choice of instrument - i.e. if power data and heart rate data are both sometimes used the results must display consistency in the long run.
4.  If heart rate and power data are both missing from some or all activities the stress arising from those activities must still be well and consistently modelled.
5.  Stress from activities over time should be aggregated in a way that again must be credible and not opaque.
6.  It should be easy for any user to compare their aggregate monthly or seasonal stress against age-group peers and to see whether they are doing statistically more or less than their peer population.
7.  To the extent possible, the cause of significant differences - for example, more or less intensity, or more or less exercise time - should be shown.

This is exactly what Crickles does. We're still working on finding the best way to present the models (point 2) but the intent is there as you can see in the **Research** section.

Crickles also picks out certain anomalies in heart rate data from your device and may help you to identify a malfunctioning chest strap or even a pattern of irregularity that may warrant attention, although Crickles itself is in no sense a medical tool and cannot diagnose your cardiac health.

## Medical disclaimer

To repeat, Crickles is in no sense a medical tool and cannot diagnose your cardiac health. Also, there is no generally accepted agreement on how best to quantify cardiac stress through exercise; Crickles aims to come up with a sensible, high-quality measure in the absence of established science.

On the other hand, Mark, the Crickles cardiologist, does respond to questions from the Crickles community as best he can.

## Privacy policy

Crickles will never disclose any identifying information about you to a third party. “Identifying information” includes your name, your date of birth, activity location data or the name you’ve given to any activity. We do not seek to identify your IP address and we do not, nor will we ever, make money from selling your data.

We *do* use your data to explore patterns of health, fitness and exercise and to try to make Crickles as useful as possible. Data published in any research or online articles will also be completely anonymised

## Infrastructure

Crickles runs on Amazon Web Services cloud infrastructure. Since the website and Navigator are free to access yet incur cost, there is less redundancy (and hence resilience) than you might expect in an app that carries a monthly usage charge. The up-time over many years consistently stands at over 99% but it can, rarely, falter under volume surges or on account of sporadic technical issues. If you see anything that doesn't look right please do get in touch to let us know, while being thankful for the fact that Crickles is free and usually reliable!
